Bug Fix: UTF-16 surrogate pairs not handled
This fixes the following bug:

What steps will reproduce the problem?
1. fetchall() on a query that produces string values that contains a
character which a 4-byte UTF-16 representation (surrogate pair). For
instance the emoji smiley u'\U0001f604'.

What is the expected output? What do you see instead?
The string values should be parsed correctly. However this exception is
thrown:

UnicodeDecodeError: 'utf16' codec can't decode bytes in position 0-1:
unexpected end of data

I think the problem is that UCS_dec() assumes that a character is always
exactly one ucs_length long.